myTransH evaluate_decom_without_raw : evaluate_decom_without_raw_detail.cpp myTransH.cpp
	g++ -o evaluate_decom_without_raw evaluate_decom_without_raw_detail.cpp -larmadillo -std=c++11
	g++ -o myTransH myTransH.cpp -larmadillo -std=c++11

clean: 
	rm evaluate_decom_without_raw
	rm myTransH
