
myTransH evaluate_decom_without_orginal : evaluate_0125.cpp myTransH.cpp
	g++ -o evaluate_decom_without_orginal evaluate_0125.cpp -larmadillo -std=c++11
	g++ -o myTransH myTransH.cpp -larmadillo -std=c++11

clean: 
	rm evaluate_decom_without_orginal
	rm myTransH
